name: "SmarterASP.NET Web Deploy"
description: "Deploy projects directly to SmarterASP.NET IIS"
inputs:
  website-name:
    description: "IIS website name"
    required: true
  server-computer-name:
    description: "IIS server computer name"
    required: true
  server-username:
    description: "IIS server username"
    required: true
  server-password:
    description: "IIS server password"
    required: true
  source-path:
    description: "The source directory for payload"
    required: false
    default: '\publish\'
  target-path:
    description: "The target directory for payload"
    required: false
    default: '""'
  target-delete:
    description: "Delete files on the destination computer that do not exist on the source computer"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Deploy Application
      shell: pwsh
      run: >
        ${{ github.action_path }}/Scripts/Deploy-ApplicationPackage.ps1
        ${{ inputs.source-path }}
        ${{ inputs.target-path }}
        ${{ inputs.website-name }}
        ${{ inputs.server-computer-name }}
        ${{ inputs.server-username }}
        ${{ inputs.server-password }}
        ${{ inputs.target-delete }}
branding:
  icon: "upload-cloud"
  color: "Green"
